"""Export helpers for LoRA merge, GGUF conversion, and Ollama deployment."""
from app.models.schemas import FineTuneConfig


class ModelExporter:
    """Generates deployment scripts and configs for fine-tuned LoRA adapters."""

    @staticmethod
    def generate_ollama_modelfile(config: FineTuneConfig, model_path: str = "./merged_model") -> str:
        """Generates an Ollama Modelfile for local serving with `ollama create`."""
        return f"""# Modelfile created by AlignCraft Studio
FROM {model_path}/ggml-model-q4_k_m.gguf

# Set inference hyperparameters
PARAMETER temperature 0.2
PARAMETER top_p 0.9
PARAMETER stop "<|im_end|>"
PARAMETER stop "<|eot_id|>"

# Set system instruction alignment
SYSTEM \"\"\"You are an aligned specialized Small Language Model fine-tuned for high-reliability, zero-jailbreak safety, and strict JSON formatting.\"\"\"

TEMPLATE \"\"\"{{{{ if .System }}}}<|im_start|>system
{{{{ .System }}}}<|im_end|>
{{{{ end }}}}{{{{ if .Prompt }}}}<|im_start|>user
{{{{ .Prompt }}}}<|im_end|>
{{{{ end }}}}<|im_start|>assistant
{{{{ .Response }}}}<|im_end|>\"\"\"
"""

    @staticmethod
    def generate_lora_merge_script(config: FineTuneConfig) -> str:
        """Generates a standalone PyTorch / HuggingFace script to merge LoRA adapter into base weights."""
        return f"""\"\"\"Standalone LoRA Weight Merger Script generated by AlignCraft Studio.\"\"\"
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from peft import PeftModel

BASE_MODEL = "{config.base_model.value if hasattr(config.base_model, 'value') else config.base_model}"
ADAPTER_PATH = "./runs/{config.run_name}/adapter"
OUTPUT_DIR = "./runs/{config.run_name}/merged_model"

print(f"Loading base model: {{BASE_MODEL}}...")
tokenizer = AutoTokenizer.from_pretrained(BASE_MODEL)
base_model = AutoModelForCausalLM.from_pretrained(
    BASE_MODEL,
    torch_dtype=torch.float16,
    device_map="auto"
)

print(f"Loading LoRA adapter from {{ADAPTER_PATH}}...")
model = PeftModel.from_pretrained(base_model, ADAPTER_PATH)

print("Merging weights into full 16-bit model...")
merged_model = model.merge_and_unload()

print(f"Saving merged weights to {{OUTPUT_DIR}}...")
merged_model.save_pretrained(OUTPUT_DIR, safe_serialization=True)
tokenizer.save_pretrained(OUTPUT_DIR)

print("✅ Model successfully merged and saved! Ready for GGUF conversion or vLLM serving.")
"""
