"""PyTorch and HuggingFace PEFT / SFTTrainer orchestrator for QLoRA."""
import os
import json
from app.models.schemas import FineTuneConfig


class QLoRATrainerGenerator:
    """Generates production-grade HuggingFace QLoRA SFT training scripts."""

    @staticmethod
    def generate_training_script(config: FineTuneConfig, dataset_path: str, output_dir: str) -> str:
        model_id = config.base_model.value if hasattr(config.base_model, 'value') else str(config.base_model)
        
        return f"""\"\"\"
Production QLoRA Supervised Fine-Tuning (SFT) Script
Generated by AlignCraft Studio
\"\"\"
import os
import torch
from datasets import load_dataset
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    BitsAndBytesConfig,
    TrainingArguments
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from trl import SFTTrainer

# 1. Model & Data Paths
MODEL_ID = "{model_id}"
DATASET_PATH = "{dataset_path}"
OUTPUT_DIR = "{output_dir}"

# 2. 4-bit Quantization Config (QLoRA)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16,
    bnb_4bit_use_double_quant=True
)

# 3. Load Tokenizer & Base Model
print(f"Loading tokenizer & quantized base model: {{MODEL_ID}}...")
tokenizer = AutoTokenizer.from_pretrained(MODEL_ID, trust_remote_code=True)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    trust_remote_code=True
)

model = prepare_model_for_kbit_training(model)

# 4. LoRA Adapter Configuration
peft_config = LoraConfig(
    r={config.lora_r},
    lora_alpha={config.lora_alpha},
    lora_dropout={config.lora_dropout},
    target_modules={json.dumps(config.target_modules)},
    bias="none",
    task_type="CAUSAL_LM"
)

# 5. Training Arguments
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    per_device_train_batch_size={config.batch_size},
    gradient_accumulation_steps={config.gradient_accumulation_steps},
    learning_rate={config.learning_rate},
    lr_scheduler_type="{config.lr_scheduler}",
    warmup_ratio={config.warmup_ratio},
    num_train_epochs={config.epochs},
    logging_steps=1,
    save_strategy="epoch",
    fp16=not torch.cuda.is_bf16_supported(),
    bf16=torch.cuda.is_bf16_supported(),
    optim="paged_adamw_8bit",
    report_to="none"
)

# 6. SFT Trainer
print("Starting Supervised Fine-Tuning (SFT)...")
dataset = load_dataset("json", data_files=DATASET_PATH, split="train")

trainer = SFTTrainer(
    model=model,
    train_dataset=dataset,
    peft_config=peft_config,
    dataset_text_field="text",
    max_seq_length={config.max_seq_length},
    tokenizer=tokenizer,
    args=training_args
)

trainer.train()

# 7. Save LoRA Adapter
print(f"Saving fine-tuned LoRA adapter to {{OUTPUT_DIR}}/adapter...")
trainer.model.save_pretrained(os.path.join(OUTPUT_DIR, "adapter"))
tokenizer.save_pretrained(os.path.join(OUTPUT_DIR, "adapter"))
print("✅ QLoRA training successfully completed!")
"""
